spring:
  application:
    name: kilogon-sample
  profiles:
    active: local

server:
  error:
    include-message: always
---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: local
  kafka:
    string-key-person-topic: StringPersonTopic
    long-key-person-topic: LongPersonTopic
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      group-id: kilogon-consumer-group
      auto-offset-reset: earliest
